openapi: 3.0.0
info:
  title: Autokis API
  description: An API for managing products for Autokis
  version: 1.0.0
#servers:
#  - url: /
paths:
  /products:
    get:
      operationId: getAllProducts
      summary: Retrieve list of Root objects
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '204':
          description: No content
components:
  schemas:
    DDResponse:
      type: object
      properties:
        status:
          type: string
        time:
          type: number
        total:
          type: integer
        totalResults:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: integer
        mark:
          type: string
        model:
          type: string
        title:
          type: string
        category:
          type: string
        subcategory:
          type: string
        manufacturer:
          type: string
        images:
          type: array
          items:
            type: string
        sku:
          type: string
        price:
          type: integer
        currency:
          type: string
        quantity:
          type: integer
        warehouse:
          type: string
        short_title:
          type: string
        parent:
          $ref: '#/components/schemas/Parent'
      readOnly: true
    Parent:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
